---
- name: installing dependencies via apt
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - openjdk-8-jdk
    - nftables
    - ulogd
    - mysql-server
    - libmysql-java
    - tomcat7
    - python-mysqldb
    - python3-requests
    - python3-setuptools
    - python3-pip
    - make
    - maven
    - pulseaudio
    - tcpdump         # Debug tools below this line
    - wget
    - curl
    - htop
    - strace

- name: jdbc directory in tomcat
  file:
    path: /usr/share/tomcat7/common
    state: directory

- name: jdbc directory in tomcat
  file:
    path: /usr/share/tomcat7/common/mysql-connector-java.jar
    src: /usr/share/java/mysql-connector-java.jar
    state: link

- include_vars: password.json

- name: tomcat7 context file
  template:
    src: context.xml
    dest: /etc/tomcat7/context.xml
    owner: root
    group: tomcat7
    mode: 0640

- name: remove tomcat default ROOT
  file:
    path: /var/lib/tomcat7/webapps/ROOT
    state: absent

- name: install runefoil
  pip:
    executable: pip3
    name: /opt/runefoil
    editable: true
    state: latest

- name: set runelite http service url via profile
  copy:
    src: runelite_api_url.sh
    dest: /etc/profile.d/runelite_api_url.sh
    mode: 0644
    owner: root
    group: root

- name: copy runefoil systemd service file
  copy:
    src: runefoil.service
    dest: /etc/systemd/system/runefoil.service
  register: runefoil_systemd

- name: reload systemd
  command: systemctl daemon-reload
  when: runefoil_systemd.changed

- import_tasks: mysql.yml
